/*Copyright 2022 Guillaume Spalla

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.*/

using Microsoft.MixedReality.Toolkit.UI;
using Microsoft.MixedReality.Toolkit.UI.BoundsControl;
using Microsoft.MixedReality.Toolkit.Utilities.Solvers;
using Microsoft.MixedReality.Toolkit.Input;
using System;
using System.Collections.Generic;
using UnityEngine;
using System.Timers;
using System.Reflection;
using System.Linq;
using MATCH.Assistances;
using NPBehave;

namespace MATCH
{
    namespace Scenarios
    {
        namespace BehaviorTrees
        {
            public class Tutorial : Scenarios.BehaviorTrees.BehaviorTree
            {
                private Inferences.Manager InferenceManager;
                public Assistances.Surfaces.Manager SurfacesManager;
                private bool surfaceTouched = false;

                // Below: generated by the Excel file
                string ConditionBeginning = "Beginning";
                string ConditionShowingExclamation = "ConditionShowingExclamation";
                string ConditionLine = "ConditionLine";
                string ConditionFollowingDialog = "ConditionFollowingDialog";
                string ConditionLookAround = "ConditionLookAround";
                string ConditionBeginningClicked = "BeginningClicked";
                string ConditionCubeFocused = "CubeFocused";
                string ConditionNextClicked = "NextClicked";
                string ConditionPenGrabbed = "PenGrabbed";
                private string ConditionSurfaceToClean = "ConditionSurfaceToClean";

                // End of Excel file generation

                // Interaction surface
                Assistances.InteractionSurface InteractionSurfaceDialogs;
                //Assistances.InteractionSurface InteractionCube;
                Assistances.InteractionSurface InteractionPen;
                Assistances.InteractionSurface InteractionExclamationMark;
                Assistances.InteractionSurface InteractionLinePointB;
                Assistances.InteractionSurface InteractionLookAround;
                Assistances.InteractionSurface InteractionDiamond;
                Assistances.InteractionSurface InteractionSurfaceToClean;
                //Assistances.InteractionSurface InteractionSurfaceToCleanDialog;

                

                Dictionary<Assistances.AssistanceGradationExplicit, bool> AssistancesDusting;

                // Cube
                //public Utilities.EyeTrackerMRTKTest Cube;

                Assistances.Icon Diamond;

                public override void Awake()
                {
                    base.Awake();
                    SetId("Nettoyer la table");
                    AssistancesDusting = new Dictionary<Assistances.AssistanceGradationExplicit, bool>();
                }

                public override void Start()
                {
                    // Initialize assistances
                    InitializeAssistances();

                    // Initialize inference manager
                    InferenceManager = MATCH.Inferences.Factory.Instance.CreateManager(transform);

                    // Initialize Losange
                    Diamond = Assistances.Factory.Instance.CreateIcon(true, new Vector3(0, 0, 0), new Vector3(0.5f, 0.5f, 0.5f), true, InteractionDiamond.transform, /*null*/Utilities.Materials.Icon.Diamond, Utilities.Materials.Colors.RedGlowing);

                    // Call base function
                    base.Start();

                    Init();

                    // Initialize debug buttons
                    InitializeDebugButtons();
                }

                protected override Root InitializeBehaviorTree()
                {
                    // Making the conditions update. SEE EXCEL SHEET TO GENERATE THE CODE BELOW
                    AddCondition(ConditionBeginning, false);
                    AddCondition(ConditionShowingExclamation, false);
                    AddCondition(ConditionLine, false);
                    AddCondition(ConditionFollowingDialog, false);
                    AddCondition(ConditionLookAround, false);
                    AddCondition(ConditionBeginningClicked, false);
                    AddCondition(ConditionCubeFocused, false);
                    AddCondition(ConditionNextClicked, false);
                    AddCondition(ConditionSurfaceToClean, false);
                    AddCondition(ConditionPenGrabbed, false);

                    int nbConditions = GetNumberOfConditions();

                    AddConditionsUpdate(ConditionBeginning, new bool[] { true, false, false, false, false, false, false, false, false, false });
                    AddConditionsUpdate(ConditionShowingExclamation, new bool[] { false, true, false, false, false, false, false, false, false, false });
                    AddConditionsUpdate(ConditionLine, new bool[] { false, false, true, false, false, false, false, false, false, false });
                    AddConditionsUpdate(ConditionFollowingDialog, new bool[] { false, false, false, true, false, false, false, false, false, false });
                    AddConditionsUpdate(ConditionLookAround, new bool[] { false, false, false, false, true, false, false, false, false, false });
                    AddConditionsUpdate(ConditionBeginningClicked, new bool[] { false, false, false, false, false, true, false, false, false, false }); ;
                    AddConditionsUpdate(ConditionCubeFocused, new bool[] { false, false, false, false, false, false, true, false, false, false });
                    AddConditionsUpdate(ConditionNextClicked, new bool[] { false, false, false, false, false, false, false, true, false, false });
                    AddConditionsUpdate(ConditionSurfaceToClean, new bool[] { false, false, false, false, false, false, false, false, true, false });
                    AddConditionsUpdate(ConditionPenGrabbed, new bool[] { false, false, false, false, false, false, false, false, false, true });


                    UpdateConditionWithMatrix(ConditionBeginning);

                    // End of code generation using the EXCEL file

                    // Defining the BT
                    Selector srBegin = new Selector(
                        new BlackboardCondition(ConditionBeginning, Operator.IS_EQUAL, true, Stops.IMMEDIATE_RESTART,
                            AssistanceAlpha()),
                        new BlackboardCondition(ConditionShowingExclamation, Operator.IS_EQUAL, true,
                            Stops.IMMEDIATE_RESTART, AssistanceBeta()),
                        new BlackboardCondition(ConditionLine, Operator.IS_EQUAL, true, Stops.IMMEDIATE_RESTART,
                            AssistanceEta()),
                        new BlackboardCondition(ConditionFollowingDialog, Operator.IS_EQUAL, true, Stops.IMMEDIATE_RESTART, AssistanceTheta()),
                        new BlackboardCondition(ConditionLookAround, Operator.IS_EQUAL, true, Stops.IMMEDIATE_RESTART, AssistanceIota()),
                        new BlackboardCondition(ConditionBeginningClicked, Operator.IS_EQUAL, true, Stops.IMMEDIATE_RESTART, AssistanceGamma()),
                        new BlackboardCondition(ConditionCubeFocused, Operator.IS_EQUAL, true, Stops.IMMEDIATE_RESTART, AssistanceDelta()),
                        new BlackboardCondition(ConditionNextClicked, Operator.IS_EQUAL, true, Stops.IMMEDIATE_RESTART, AssistanceEpsilon()),
                        new BlackboardCondition(ConditionSurfaceToClean, Operator.IS_EQUAL, true, Stops.IMMEDIATE_RESTART, AssistanceKappa()),
                        new BlackboardCondition(ConditionPenGrabbed, Operator.IS_EQUAL, true, Stops.IMMEDIATE_RESTART, AssistanceZeta()));

                    Root tree = new Root(/*Conditions*/Getconditions(), srBegin);

                    return tree;
                }

                void InitializeDebugButtons()
                {
                    
                    
                }

                void InitializeAssistances()
                {
                    InteractionSurfaceDialogs = Assistances.Factory.Instance.CreateInteractionSurface("Tutorial - Introduction - Cyan", AdminMenu.Panels.Right, new Vector3(1.1f, 0.02f, 0.7f), new Vector3(-0.447f, -0.406f, 0.009f), Utilities.Materials.Colors.CyanGlowing, false, true, Utilities.Utility.GetEventHandlerEmpty(), true, transform);

                    InteractionExclamationMark = Assistances.Factory.Instance.CreateInteractionSurface("Tutorial - Exclamation Mark - Red", AdminMenu.Panels.Right, new Vector3(0.1f, 0.1f, 0.1f), new Vector3(0.4f, -0.406f, -0.7f), Utilities.Materials.Colors.RedGlowing, false, true, Utilities.Utility.GetEventHandlerEmpty(), true, transform);

                    InteractionLinePointB = Assistances.Factory.Instance.CreateInteractionSurface("Tutorial - Line - Green", AdminMenu.Panels.Right, new Vector3(0.1f, 0.1f, 0.1f), new Vector3(0.4f, -0.406f, -0.7f), Utilities.Materials.Colors.GreenGlowing, false, true, Utilities.Utility.GetEventHandlerEmpty(), true, transform);

                    InteractionLookAround = Assistances.Factory.Instance.CreateInteractionSurface("Tutorial-Look Around - White", AdminMenu.Panels.Right, new Vector3(0.1f, 0.1f, 0.1f), new Vector3(0.4f, -0.406f, -0.7f), Utilities.Materials.Colors.WhiteMetallic, false, true, Utilities.Utility.GetEventHandlerEmpty(), true, transform);

                    InteractionDiamond = Assistances.Factory.Instance.CreateInteractionSurface("Tutorial - Losange - Yellow", AdminMenu.Panels.Right, new Vector3(0.1f, 0.1f, 0.1f), new Vector3(0.4f, -0.406f, -0.7f), Utilities.Materials.Colors.YellowGlowing, false, true, Utilities.Utility.GetEventHandlerEmpty(), true, transform);

                    /*InteractionCube = Assistances.Factory.Instance.CreateInteractionSurface("Tutorial-Cube (ORANGE)", AdminMenu.Panels.Right, new Vector3(0.1f, 0.02f, 0.1f), new Vector3(-0.9f, -0.406f, -0.7f), Utilities.Materials.Colors.OrangeGlowing, false, true, Utilities.Utility.GetEventHandlerEmpty(), true, transform);*/

                    InteractionPen = Assistances.Factory.Instance.CreateInteractionSurface("Tutorial - Pen - Purple", AdminMenu.Panels.Right, new Vector3(0.1f, 0.1f, 0.1f), new Vector3(-0.1f, -0.406f, -0.7f), Utilities.Materials.Colors.PurpleGlowing, false, true, Utilities.Utility.GetEventHandlerEmpty(), true, transform);
                    
                    InteractionSurfaceToClean = Assistances.Factory.Instance.CreateInteractionSurface("Tutorial - Surface to clean - Orange", AdminMenu.Panels.Right, new Vector3(0.1f, 0.1f, 0.1f), new Vector3(0.4f, -0.406f, -0.7f), Utilities.Materials.Colors.OrangeAdjustHSV, false, true, Utilities.Utility.GetEventHandlerEmpty(), true, transform);
                    
                    /*InteractionSurfaceToCleanDialog = Assistances.Factory.Instance.CreateInteractionSurface("Tutorial - Surface to clean dialog - Orange", AdminMenu.Panels.Right, new Vector3(0.1f, 0.1f, 0.1f), new Vector3(0.4f, -0.406f, -0.7f), Utilities.Materials.Colors.OrangeGlowing, false, true, Utilities.Utility.GetEventHandlerEmpty(), true, transform);*/

                }

                Sequence AssistanceAlpha()
                {
                    /*Assistances.GradationVisual.GradationVisual alpha1 = Assistances.GradationVisual.Factory.Instance.CreateDialogOneButton("Tutorial-Alpha-1", "", "Bienvenue! Voici un tutoriel pour vous familiariser avec cette assistance. Pour commencer, avec un doigt, touchez le bouton \"Commencer !\" ci-dessous, comme si vous touchiez un interrupteur.", "Commencer !", delegate(System.Object o, EventArgs e)
                    {
                        UpdateConditionWithMatrix(ConditionBeginningClicked);
                    }, Assistances.Buttons.Button.ButtonType.ClosingButton, InteractionSurfaceDialogs.transform);*/

                    Assistances.GradationVisual.GradationVisual alpha1 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-Alpha-1", "", "Bienvenue! Voici un tutoriel pour vous familiariser avec ce système. Pour commencer, touchez le bouton \"Commencer !\" ci-dessous avec un doigt, comme si vous touchiez un interrupteur.", "Commencer !", delegate (System.Object o, EventArgs e)
                    {
                        UpdateConditionWithMatrix(ConditionShowingExclamation);
                    }, Assistances.Buttons.Button.ButtonType.ClosingButton, InteractionSurfaceDialogs.transform);


                    Assistances.AssistanceGradationExplicit alpha = MATCH.Assistances.Factory.Instance.CreateAssistanceGradationExplicit("DustingTable-Alpha");
                    alpha.transform.parent = transform;

                    alpha.AddAssistance(alpha1, Assistances.Buttons.Button.ButtonType.ClosingButton, null);

                    //////////Line to delete [FOR TEST ONLY]
                    alpha.AddAssistance(alpha1, Assistances.Buttons.Button.ButtonType.CustomChoice1, null);

                    AssistancesDusting.Add(alpha, false);

                    alpha.Init();

                    Sequence temp = new Sequence(
                        new NPBehave.Action(() => {
                            ShowAssistanceHideOthers(alpha);
                            InferenceManager.UnregisterAllInferences();
                            UpdateTextAssistancesDebugWindow("Alpha");
                            MATCH.Utilities.Logger.Instance.Log(this.GetId(), MethodBase.GetCurrentMethod().ReflectedType.Name, MethodBase.GetCurrentMethod().Name, "Alpha");
                        }),
                        new WaitUntilStopped()
                        );

                    return temp;
                }

                Sequence AssistanceBeta()
                {
                    Assistances.GradationVisual.GradationVisual beta1 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-ExclamationMarkDialog", "", "Vous allez maintenant voir un point d'exclamation. Il apparait pour attirer votre attention sur une action à réaliser. Appuyez sur le bouton \"Suivant\" ci-dessous pour voir un exemple", "Suivant", null, Assistances.Buttons.Button.ButtonType.Yes, InteractionSurfaceDialogs.transform);
                    Assistances.GradationVisual.GradationVisual beta2 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-ExclamationMarkDialog-2", "", "Vous pouvez voir un point d'exclamation sur votre droite. Le point d'exclamation, comme d'autres éléments, peut prendre différentes couleurs. Touchez le bouton \"Suivant\" ci-dessous.", "Suivant", null, Assistances.Buttons.Button.ButtonType.Yes, InteractionSurfaceDialogs.transform);
                    Assistances.GradationVisual.GradationVisual beta2a = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-ExclamationMarkDialog-2a", "", "Pour vous donner un exemple, le point d'exclamation va changer de couleur si vous touchez le bouton \"Suivant\" ci-dessous.", "Suivant", null, Assistances.Buttons.Button.ButtonType.Yes, InteractionSurfaceDialogs.transform);
                    Assistances.GradationVisual.GradationVisual beta3 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-ExclamationMarkDialog-3", "", "Le point d'exclamation est maintenant orange. Si vous ne le regardez toujours pas, il deviendra rouge. Appuyez sur \"Suivant\" pour voir un exemple.", "Suivant", null, Assistances.Buttons.Button.ButtonType.Yes, InteractionSurfaceDialogs.transform);
                    Assistances.GradationVisual.GradationVisual beta4 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-ExclamationMarkDialog-4", "", "Le point d'exclamation est maintenant rouge.", "Suivant", null, Assistances.Buttons.Button.ButtonType.Yes, InteractionSurfaceDialogs.transform);
                    Assistances.GradationVisual.GradationVisual beta5 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-ExclamationMarkDialog-5", "", "Le point d'exclamation peut également vous proposer plus d'aide si vous ne comprenez pas à quoi il fait référence. Appuyez sur \"Suivant\" pour voir un exemple.", "Suivant", null, Assistances.Buttons.Button.ButtonType.Yes, InteractionSurfaceDialogs.transform);
                    Assistances.GradationVisual.GradationVisual beta6 = Assistances.GradationVisual.Factory.Instance.CreateDialog2NoButton("Tutorial-ExclamationMarkDialog-6", "", "Vous pouvez voir les boutons d'aide sous le point d'exclamation. Appuyez sur un de ces boutons pour continuer le tutoriel.", InteractionSurfaceDialogs.transform);



                    Assistances.Icon assistanceExclamation = Assistances.Factory.Instance.CreateIcon(true, new Vector3(0, 0, 0), new Vector3(0.15f, 0.15f, 0.15f), true, InteractionExclamationMark.transform, /*null*/Utilities.Materials.Icon.ExclamationMark, Utilities.Materials.Colors.WhiteMetallic);
                    assistanceExclamation.transform.Find("Child").localPosition = new Vector3(0, (float)0.33, 0);
                    
                    Assistances.AssistanceGradationExplicit beta = MATCH.Assistances.Factory.Instance.CreateAssistanceGradationExplicit("Tutorial-Beta");

                    beta.transform.parent = transform;
                    beta.AddAssistance(beta1, Assistances.Buttons.Button.ButtonType.Yes, beta2);
                    beta.AddAssistance(beta2, Assistances.Buttons.Button.ButtonType.Yes, beta2a);
                    beta.AddAssistance(beta2a, Assistances.Buttons.Button.ButtonType.Yes, beta3);
                    beta.AddAssistance(beta3, Assistances.Buttons.Button.ButtonType.Yes, beta4);
                    beta.AddAssistance(beta4, Assistances.Buttons.Button.ButtonType.Yes, beta5);
                    beta.AddAssistance(beta5, Assistances.Buttons.Button.ButtonType.Yes, beta6);
                    beta.AddAssistance(beta6, Assistances.Buttons.Button.ButtonType.Yes, null);



                    AssistancesDusting.Add(beta, false);

                    Assistances.IAssistance beta1IAssistance = (Assistances.IAssistance)beta1.GetCurrentAssistance();
                    Assistances.Assistance beta1Assistance = (Assistances.Assistance)beta1IAssistance.GetRootDecoratedAssistance();

                    Assistances.IAssistance beta2IAssistance = (Assistances.IAssistance)beta2.GetCurrentAssistance();
                    Assistances.Assistance beta2Assistance = (Assistances.Assistance)beta2IAssistance.GetRootDecoratedAssistance();

                    Assistances.IAssistance beta3IAssistance = (Assistances.IAssistance)beta3.GetCurrentAssistance();
                    Assistances.Assistance beta3Assistance = (Assistances.Assistance)beta3IAssistance.GetRootDecoratedAssistance();
                    
                    Assistances.IAssistance beta4IAssistance = (Assistances.IAssistance)beta4.GetCurrentAssistance();
                    Assistances.Assistance beta4Assistance = (Assistances.Assistance)beta4IAssistance.GetRootDecoratedAssistance();
                    
                    Assistances.IAssistance beta5IAssistance = (Assistances.IAssistance)beta5.GetCurrentAssistance();
                    Assistances.Assistance beta5Assistance = (Assistances.Assistance)beta5IAssistance.GetRootDecoratedAssistance();



                    beta.Init();
                    beta1Assistance.EventHelpButtonClicked += delegate (System.Object o, EventArgs e)
                    {
                        assistanceExclamation.Show(Utilities.Utility.GetEventHandlerEmpty(), false);
                    };

                    beta2Assistance.EventHelpButtonClicked += delegate (System.Object o, EventArgs e)
                    {
                        assistanceExclamation.SetMaterial(Utilities.Materials.Colors.OrangeGlowing);
                    };

                    beta3Assistance.EventHelpButtonClicked += delegate (System.Object o, EventArgs e)
                    {
                        assistanceExclamation.SetMaterial(Utilities.Materials.Colors.RedGlowing);
                    };
                    
                    beta4Assistance.EventHelpButtonClicked += delegate (System.Object o, EventArgs e)
                    {
                        assistanceExclamation.SetMaterial(Utilities.Materials.Colors.WhiteMetallic);
                    };
                    
                    beta5Assistance.EventHelpButtonClicked += delegate (System.Object o, EventArgs e)
                    {
                        assistanceExclamation.ShowHelp(true, Utilities.Utility.GetEventHandlerEmpty(), true);

                        assistanceExclamation.EventHelpButtonClicked += delegate(object sender, EventArgs args)
                        {
                            assistanceExclamation.Hide(Utilities.Utility.GetEventHandlerEmpty(), false);
                            UpdateConditionWithMatrix(ConditionLine);
                        };
                    };

                    Sequence temp = new Sequence(
                        new NPBehave.Action(() => {
                            ShowAssistanceHideOthers(beta);
                            InferenceManager.UnregisterAllInferences();
                            UpdateTextAssistancesDebugWindow("Beta");
                            MATCH.Utilities.Logger.Instance.Log(this.GetId(), MethodBase.GetCurrentMethod().ReflectedType.Name, MethodBase.GetCurrentMethod().Name, "Beta");
                        }),
                        new WaitUntilStopped()
                        );

                    return temp;
                }

                Sequence AssistanceEta()
                {
                    Assistances.Decorators.LinePath decorator4 = new Assistances.Decorators.LinePath();
                    Assistances.Decorators.LinePath decorator5 = new Assistances.Decorators.LinePath();
                    Assistances.GradationVisual.GradationVisual eta1 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-LineDialog-1", "", "Pour vous indiquer un endroit où continuer à réaliser votre activité, le système peut vous diriger en faisant apparaitre devant vous une ligne pour vous guider. Appuyez sur \"Suivant\" pour faire apparaitre une ligne et suivez-la pour continuer le tutoriel.", "Suivant", null, Assistances.Buttons.Button.ButtonType.Yes, InteractionSurfaceDialogs.transform);
                    Assistances.GradationVisual.GradationVisual eta2 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-LineDialog-2", "", "Bravo ! Vous êtes bien arrivé là où la ligne vous guidait.", "Suivant", null, Assistances.Buttons.Button.ButtonType.Yes, InteractionLinePointB.transform);
                    Assistances.GradationVisual.GradationVisual eta3 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-LineDialog-3", "", "Le système peut aussi faire apparaître un texte devant vous, et qui vous suivra dans vos déplacements. Appuyez sur \"Suivant\" pour voir un exemple.", "Suivant", delegate(object o, EventArgs e)
                    {
                        UpdateConditionWithMatrix(ConditionFollowingDialog);
                    }, Assistances.Buttons.Button.ButtonType.Yes, InteractionLinePointB.transform);

                    

                    Assistances.AssistanceGradationExplicit eta = MATCH.Assistances.Factory.Instance.CreateAssistanceGradationExplicit("Tutorial-Eta");

                    eta.transform.parent = transform;
                    eta.AddAssistance(eta1, Assistances.Buttons.Button.ButtonType.Yes, eta2);
                    eta.AddAssistance(eta2, Assistances.Buttons.Button.ButtonType.Yes, eta3);
                    eta.AddAssistance(eta3, Assistances.Buttons.Button.ButtonType.Yes, null);
                    
                    AssistancesDusting.Add(eta, false);
                    
                    Assistances.IAssistance eta1IAssistance = (Assistances.IAssistance)eta1.GetCurrentAssistance();
                    Assistances.Assistance eta1Assistance = (Assistances.Assistance)eta1IAssistance.GetRootDecoratedAssistance();
                    
                    Assistances.IAssistance eta2IAssistance = (Assistances.IAssistance)eta2.GetCurrentAssistance();
                    Assistances.Assistance eta2Assistance = (Assistances.Assistance)eta2IAssistance.GetRootDecoratedAssistance();

                    eta.Init();
                    MATCH.Inferences.Manager InferenceManager = MATCH.Inferences.Factory.Instance.CreateManager(transform);
                    eta1Assistance.EventHelpButtonClicked += delegate(System.Object o, EventArgs e)
                    {
                        decorator4 =
                            (Assistances.Decorators.LinePath)Assistances.Decorators.Factory.Instance
                                .CreateLinePathWithTexture(eta2IAssistance, /*Utilities.Materials.Colors.Orange*/
                                    /*Utilities.Materials.Textures.ArrowProgressive*/ Utilities.Materials.Colors.CyanAdjustHSV, /*0.1f*/ 0.039f, true);

                        decorator4.Show(Utilities.Utility.GetEventHandlerEmpty(), false);
                        
                        // Make the line disapear when user is close to arriving assistance
                        MATCH.Inferences.Factory.Instance.CreateDistanceComingInferenceOneShot(InferenceManager, "1",
                            delegate(object o, EventArgs e)
                            {
                                decorator4.GetAssistance().gameObject.SetActive(false);

                            }, /*eta2.gameObject*/((IAssistance)eta2.GetCurrentAssistance()).GetDecoratedAssistance().gameObject, 1.3F);
                        
                    };
                    
                    
                    
                    

                    Sequence temp = new Sequence(
                        new NPBehave.Action(() => {
                            ShowAssistanceHideOthers(eta);
                            InferenceManager.UnregisterAllInferences();
                            UpdateTextAssistancesDebugWindow("Eta");
                            MATCH.Utilities.Logger.Instance.Log(this.GetId(), MethodBase.GetCurrentMethod().ReflectedType.Name, MethodBase.GetCurrentMethod().Name, "Eta");
                        }),
                        new WaitUntilStopped()
                    );

                    return temp;
                }
                

                Sequence AssistanceTheta()
                {
                    Assistances.GradationVisual.GradationVisual theta1 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-Following-1", "", "Ce texte vous suit! Marchez un peu et tournez la tête pour vous en rendre compte. Quand vous le souhaiterez, appuyez sur le bouton \"Suivant\" pour continuer.", "Suivant", null, Assistances.Buttons.Button.ButtonType.Yes, MATCH.Assistances.InteractionSurfaceFollower.Instance.transform);

                    Assistances.AssistanceGradationExplicit theta = MATCH.Assistances.Factory.Instance.CreateAssistanceGradationExplicit("Tutorial-Theta");

                    theta.transform.parent = transform;
                    theta.AddAssistance(theta1, Assistances.Buttons.Button.ButtonType.Yes, null);

                    AssistancesDusting.Add(theta, false);
                    
                    Assistances.IAssistance theta1IAssistance = (Assistances.IAssistance)theta1.GetCurrentAssistance();
                    Assistances.Assistance theta1Assistance = (Assistances.Assistance)theta1IAssistance.GetRootDecoratedAssistance();
                    

                    theta.Init();
                    
                    theta1Assistance.EventHelpButtonClicked += delegate(System.Object o, EventArgs e)
                    {
                        UpdateConditionWithMatrix(ConditionLookAround);
                    };

                        Sequence temp = new Sequence(
                        new NPBehave.Action(() => {
                            ShowAssistanceHideOthers(theta);
                            InferenceManager.UnregisterAllInferences();
                            UpdateTextAssistancesDebugWindow("Eta");
                            MATCH.Utilities.Logger.Instance.Log(this.GetId(), MethodBase.GetCurrentMethod().ReflectedType.Name, MethodBase.GetCurrentMethod().Name, "Eta");
                        }),
                        new WaitUntilStopped()
                    );

                    return temp;
                }

                Sequence AssistanceIota()
                {
                    Assistances.Decorators.LinePath lineDecorator = new Assistances.Decorators.LinePath();
                    Assistances.GradationVisual.GradationVisual lota0 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-LookAround-1", "", "Appuyez sur le bouton \"Suivant\" pour faire apparaitre une flèche qui va vous guider à la suite du tutoriel.", "Suivant", null, Assistances.Buttons.Button.ButtonType.Yes, MATCH.Assistances.InteractionSurfaceFollower.Instance.transform);
                    
                    Assistances.GradationVisual.GradationVisual iota1 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-LookAround-1", "", "Vous êtes au bon endroit! Le casque que vous portez a une limitation qui fait que vous ne pouvez pas voir des informations qui apparaissent à la périphérie de votre champs de vision. Il faut donc que vous pensiez à tourner la tête pour ne manquer aucune information. Appuyez sur \"Suivant\" pour voir un exemple.", "Suivant", null, Assistances.Buttons.Button.ButtonType.Yes, InteractionLookAround.transform);
                    Assistances.IAssistance iota1Iassistance = ((Assistances.IAssistance) iota1.GetCurrentAssistance());
                    Assistances.Dialogs.Dialog2 iota1Dialog = ((Assistances.Dialogs.Dialog2)iota1Iassistance.GetRootDecoratedAssistance());
                    iota1Dialog.GetComponent<Billboard>().enabled = false; // We disable the billboard to make sure the person will be at the right position to look at the diamond


                    Assistances.GradationVisual.GradationVisual iota2 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-LookAround-2", "", "Pour illustrer cela, un losange rouge est apparu sur votre droite. Vous le verrez si vous tournez votre tête. Une fois que vous l'avez trouvé, appuyez sur le bouton \"Suivant\" pour continuer.", "Suivant", null, Assistances.Buttons.Button.ButtonType.Yes, InteractionLookAround.transform);
                    

                    /*Assistances.Icon Losange = Assistances.Factory.Instance.CreateIcon(true, new Vector3(0, 0, 0), new Vector3(0.5f, 0.5f, 0.5f), true, InteractionLosange.transform, Utilities.Materials.Icon.Diamond, Utilities.Materials.Colors.RedGlowing);*/
                    
                    Assistances.AssistanceGradationExplicit iota = MATCH.Assistances.Factory.Instance.CreateAssistanceGradationExplicit("Tutorial-Lota");

                    iota.transform.parent = transform;
                    iota.AddAssistance(lota0, Assistances.Buttons.Button.ButtonType.Yes, iota1);
                    iota.AddAssistance(iota1, Assistances.Buttons.Button.ButtonType.Yes, iota2);
                    iota.AddAssistance(iota2, Assistances.Buttons.Button.ButtonType.Yes, null);

                    AssistancesDusting.Add(iota, false);
                    
                    Assistances.IAssistance lota0IAssistance = (Assistances.IAssistance)lota0.GetCurrentAssistance();
                    Assistances.Assistance iota0Assistance = (Assistances.Assistance)lota0IAssistance.GetRootDecoratedAssistance();
                    
                    Assistances.IAssistance lota1IAssistance = (Assistances.IAssistance)iota1.GetCurrentAssistance();
                    Assistances.Assistance lota1Assistance = (Assistances.Assistance)lota1IAssistance.GetRootDecoratedAssistance();

                    Assistances.IAssistance lota2IAssistance = (Assistances.IAssistance)iota2.GetCurrentAssistance();
                    Assistances.Assistance lota2Assistance = (Assistances.Assistance)lota2IAssistance.GetRootDecoratedAssistance();

                    iota.Init();
                    MATCH.Inferences.Manager InferenceManager = MATCH.Inferences.Factory.Instance.CreateManager(transform);
                    
                    iota0Assistance.EventHelpButtonClicked += delegate(object o, EventArgs e)
                    {
                        lineDecorator = (Assistances.Decorators.LinePath)Assistances.Decorators.Factory.Instance
                            .CreateLinePathWithTexture(lota1IAssistance, /*Utilities.Materials.Colors.Orange*/
                                /*Utilities.Materials.Textures.ArrowProgressive*/ Utilities.Materials.Colors.CyanAdjustHSV, /*0.1f*/ 0.039f, true);
                    
                        lineDecorator.Show(Utilities.Utility.GetEventHandlerEmpty(), false);
                        
                        MATCH.Inferences.Factory.Instance.CreateDistanceComingInferenceOneShot(InferenceManager, "1",
                            delegate(object o, EventArgs e)
                            {
                                lineDecorator.GetAssistance().gameObject.SetActive(false);
                    
                            }, /*eta2.gameObject*/((IAssistance)iota1.GetCurrentAssistance()).GetDecoratedAssistance().gameObject, 1.3F);

                    };

                    lota1Assistance.EventHelpButtonClicked += delegate (System.Object o, EventArgs e)
                    {
                        Diamond.Show(Utilities.Utility.GetEventHandlerEmpty(), false);
                    };

                    lota2Assistance.EventHelpButtonClicked += delegate(System.Object o, EventArgs e)
                    {
                        //Diamond.Hide(Utilities.Utility.GetEventHandlerEmpty(), false);
                        UpdateConditionWithMatrix(ConditionBeginningClicked);
                    };

                    Sequence temp = new Sequence(
                        new NPBehave.Action(() => {
                            ShowAssistanceHideOthers(iota);
                            InferenceManager.UnregisterAllInferences();
                            UpdateTextAssistancesDebugWindow("Lota");
                            MATCH.Utilities.Logger.Instance.Log(this.GetId(), MethodBase.GetCurrentMethod().ReflectedType.Name, MethodBase.GetCurrentMethod().Name, "Lota");
                        }),
                        new WaitUntilStopped()
                    );

                    return temp;
                }

                Sequence AssistanceGamma()
                {
                    Assistances.GradationVisual.GradationVisual gammaBase = Assistances.GradationVisual.Factory.Instance.CreateDialog2NoButton("Tutorial-Gamma-1", "", "Le casque que vous portez comprend aussi où vous regardez. Regardez de nouveau le losange pendant quelques secondes pour passer à la suite.", /*InteractionSurfaceDialogs.transform*/InteractionLookAround.transform);

                    Assistances.AssistanceGradationExplicit gamma = MATCH.Assistances.Factory.Instance.CreateAssistanceGradationExplicit("Tutorial-Gamma");
                    gamma.transform.parent = transform;

                    gamma.AddAssistance(gammaBase, Assistances.Buttons.Button.ButtonType.ClosingButton, null);

                    AssistancesDusting.Add(gamma, false);

                    gamma.Init();

                    

                    /*Cube.gameObject.transform.parent = InteractionCube.transform;
                    Cube.transform.localPosition = new Vector3(0, 0f, 0);
                    Utilities.Utility.AdjustObjectHeightToHeadHeight(Cube.transform);
                    Cube.CubeFocused += delegate (System.Object o, EventArgs e)
                    {
                        UpdateConditionWithMatrix(ConditionCubeFocused);
                    };*/

                    Sequence temp = new Sequence(
                        new NPBehave.Action(() => {
                            ShowAssistanceHideOthers(gamma);
                            //Cube.gameObject.SetActive(true);

                            InferenceManager.UnregisterAllInferences();

                            Assistances.IAssistance gammaIAssistance = ((Assistances.IAssistance)gammaBase.GetCurrentAssistance());
                            Assistances.Dialogs.Dialog2 gammaDialog2 = ((Assistances.Dialogs.Dialog2)gammaIAssistance.GetRootDecoratedAssistance());
                            
                            gammaDialog2.EventIsShown += delegate (System.Object o, EventArgs e)
                            {
                                Inferences.ObjectFocused inf = new Inferences.ObjectFocused("Diamond focused", delegate (System.Object o, EventArgs e)
                                {
                                    UpdateConditionWithMatrix(ConditionCubeFocused);
                                    InferenceManager.UnregisterInference("Diamond focused");
                                }, Diamond.GetAssistance().GetTransform().gameObject, 3);
                                InferenceManager.RegisterInference(inf);
                            };

                            UpdateTextAssistancesDebugWindow("Gamma");
                            MATCH.Utilities.Logger.Instance.Log(this.GetId(), MethodBase.GetCurrentMethod().ReflectedType.Name, MethodBase.GetCurrentMethod().Name, "Gamma");
                        }),
                        new WaitUntilStopped()
                        );

                    return temp;
                }
                    
                Sequence AssistanceDelta()
                {
                    /*Assistances.GradationVisual.GradationVisual gamma1 = Assistances.GradationVisual.Factory.Instance.CreateDialogOneButton("Tutorial-Gamma-1", "", "Super! Comme vous le voyez, le système comprend ce que vous regardez. Il pourra donc faire certaines actions si vous regardez un objet.\nTouchez le bouton ci-dessous pour continuer.", "Suivant", delegate(System.Object o, EventArgs e)
                    {
                        UpdateConditionWithMatrix(ConditionNextClicked);
                    }, Assistances.Buttons.Button.ButtonType.ClosingButton, InteractionCube.transform);*/

                    Assistances.GradationVisual.GradationVisual delta1 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-Delta-1", "", "Le système a compris que vous regardiez le losange! Il pourra donc faire certaines actions si vous regardez un objet.", "Suivant", delegate (System.Object o, EventArgs e)
                    {
                        UpdateConditionWithMatrix(ConditionNextClicked);
                    }, Assistances.Buttons.Button.ButtonType.ClosingButton, InteractionDiamond.transform);

                    Assistances.AssistanceGradationExplicit delta = MATCH.Assistances.Factory.Instance.CreateAssistanceGradationExplicit("Tutorial-Delta");
                    delta.transform.parent = transform;

                    delta.AddAssistance(delta1, Assistances.Buttons.Button.ButtonType.ClosingButton, null);

                    AssistancesDusting.Add(delta, false);

                    delta.Init();

                    Sequence temp = new Sequence(
                        new NPBehave.Action(() => {
                            ShowAssistanceHideOthers(delta);
                            //Utilities.Utility.AnimateDisappearInPlace(Cube.gameObject, Cube.transform.localScale);
                            Diamond.Hide(Utilities.Utility.GetEventHandlerEmpty(), false);
                            //Cube.gameObject.SetActive(false);
                            InferenceManager.UnregisterAllInferences();
                            UpdateTextAssistancesDebugWindow("Delta");
                            MATCH.Utilities.Logger.Instance.Log(this.GetId(), MethodBase.GetCurrentMethod().ReflectedType.Name, MethodBase.GetCurrentMethod().Name, "Delta");
                        }),
                        new WaitUntilStopped()
                        );

                    return temp;
                }

                Sequence AssistanceEpsilon()
                {
                    /*Assistances.GradationVisual.GradationVisual delta1 = Assistances.GradationVisual.Factory.Instance.CreateDialogOneButton("Tutorial-Delta-1", "", "Une dernière chose! Il est important que vous regardiez votre main lorsque vous faites une action. Cela est dû à une limite technique du casque que vous portez. Un bouton va apparaître ci-dessous dans quelques secondes. Touchez le pour continuer.", "Suivant", Utilities.Utility.GetEventHandlerEmpty(), Assistances.Buttons.Button.ButtonType.Yes, InteractionCube.transform);*/

                    Assistances.GradationVisual.GradationVisual epsilon1 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-Epsilon-1", "", "Il est important que vous regardiez votre main lorsque vous faites une action. Cela est dû à une limite technique du casque que vous portez.", "Suivant", Utilities.Utility.GetEventHandlerEmpty(), Assistances.Buttons.Button.ButtonType.Yes, InteractionDiamond.transform);

                    /*Assistances.GradationVisual.GradationVisual delta2 = Assistances.GradationVisual.Factory.Instance.CreateDialogNoButton("Tutorial-Delta-1", "", "Pour tester cela, prenez le stylo sur votre droite. Si vous l'avez regardé correctement en le prenant, alors vous verrez un nouveau texte apparaître ici. Sinon, reposez-le au même endroit et recommencez.", InteractionCube.transform);*/

                    Assistances.GradationVisual.GradationVisual epsilon2 = Assistances.GradationVisual.Factory.Instance.CreateDialog2NoButton("Tutorial-Epsilon-1", "", "Pour tester cela, prenez le stylo sur votre droite. Si vous l'avez regardé correctement en le prenant, alors vous verrez un nouveau message apparaître ici. Sinon, reposez-le au même endroit et recommencez.", InteractionDiamond.transform);

                    Assistances.AssistanceGradationExplicit epsilon = MATCH.Assistances.Factory.Instance.CreateAssistanceGradationExplicit("Tutorial-Epsilon");
                    epsilon.transform.parent = transform;

                    epsilon.AddAssistance(epsilon1, Assistances.Buttons.Button.ButtonType.Yes, epsilon2);
                    epsilon.AddAssistance(epsilon2, Assistances.Buttons.Button.ButtonType.ClosingButton, null);

                    AssistancesDusting.Add(epsilon, false);

                    epsilon.Init();

                    InteractionPen.EventUserTouched += delegate (System.Object o, EventArgs e)
                    {
                        UpdateConditionWithMatrix(ConditionSurfaceToClean);
                    };

                    Sequence temp = new Sequence(
                        new NPBehave.Action(() => {
                            ShowAssistanceHideOthers(epsilon);
                            InferenceManager.UnregisterAllInferences();
                            UpdateTextAssistancesDebugWindow("Epsilon");
                            MATCH.Utilities.Logger.Instance.Log(this.GetId(), MethodBase.GetCurrentMethod().ReflectedType.Name, MethodBase.GetCurrentMethod().Name, "Epsilon");
                        }),
                        new WaitUntilStopped()
                        );

                    return temp;
                }

                Sequence AssistanceKappa()
                {
                    Assistances.SurfaceToProcess assistanceSurfaceToClean =
                        Assistances.Factory.Instance.CreateSurfaceToProcess(InteractionSurfaceToClean.transform,
                            InteractionSurfaceToClean, 3, 4);


                    Assistances.GradationVisual.GradationVisual kappa1 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-cleaningSurface-1", "", "Le système a vu que vous avez pris le stylo! Avant de terminer, vous allez découvrir un dernier élément qui peut apparaître.", "Suivant",
                        delegate(object sender, EventArgs args)
                        {
                            assistanceSurfaceToClean.Show(Utilities.Utility.GetEventHandlerEmpty(), false);
                        }
                        , Assistances.Buttons.Button.ButtonType.Yes, /*InteractionSurfaceToCleanDialog.transform*/ InteractionDiamond.transform);
                    Assistances.Dialogs.Dialog2 dialog1 = Assistances.Factory.Instance.CreateDialog2NoButton("",
                        "La surface a détecté que vous avez touché cette partie-là. Continuez pour que toute la surface soit verte.",
                        /*InteractionSurfaceToCleanDialog.transform*/ InteractionSurfaceToClean.transform);
                    Assistances.Decorators.BackgroundColorMessage2 dialog1Background = (Assistances.Decorators.BackgroundColorMessage2)Assistances.Decorators.Factory.Instance.CreateBackgroundMessage(dialog1, Utilities.Materials.Colors.CyanAdjustHSV);
                    Assistance dialog1BackgroundIcon = Assistances.Decorators.Factory.Instance.CreateBackgroundIcon(dialog1Background, Utilities.Materials.Colors.CyanAdjustHSV, true);

                    Assistances.GradationVisual.GradationVisual kappa2 = Assistances.GradationVisual.Factory.Instance.CreateDialog2NoButton("Tutorial-cleaningSurface-2", "", "Vous trouverez sur votre droite une surface bleue. Cette surface détecte les endroits que vous avez touché. Pour essayer, touchez une partie de la surface.",  /*InteractionSurfaceToCleanDialog.transform*/ InteractionDiamond.transform);

                    Assistances.IAssistance kappa1IAssistance = (Assistances.IAssistance)kappa1.GetCurrentAssistance();
                    Assistances.Assistance kappa1Assistance = (Assistances.Assistance)kappa1IAssistance.GetRootDecoratedAssistance();
                    
                    Assistances.IAssistance kappa2IAssistance = (Assistances.IAssistance)kappa2.GetCurrentAssistance();
                    Assistances.Assistance kappa2Assistance = (Assistances.Assistance)kappa2IAssistance.GetRootDecoratedAssistance();

                    Assistances.AssistanceGradationExplicit kappa = MATCH.Assistances.Factory.Instance.CreateAssistanceGradationExplicit("Tutorial-Kappa");

                    assistanceSurfaceToClean.EventNewPartCleaned += delegate(object sender, EventArgs args)
                    {
                        if (!surfaceTouched)
                        {
                            kappa.StopAssistance();
                            dialog1BackgroundIcon.Show(Utilities.Utility.GetEventHandlerEmpty(), false);
                        }
                    };
                    
                    assistanceSurfaceToClean.EventSurfaceCleaned += delegate(object sender, EventArgs args)
                    {
                        dialog1BackgroundIcon.Hide(Utilities.Utility.GetEventHandlerEmpty(), false);
                        assistanceSurfaceToClean.Hide(Utilities.Utility.GetEventHandlerEmpty(), false);
                        UpdateConditionWithMatrix(ConditionPenGrabbed);
                    };
                    
                    
                    kappa.transform.parent = transform;

                    kappa.AddAssistance(kappa1, Assistances.Buttons.Button.ButtonType.Yes, kappa2);
                    kappa.AddAssistance(kappa2, Assistances.Buttons.Button.ButtonType.Yes, null);

                    AssistancesDusting.Add(kappa, false);

                    kappa.Init();
                    
                    
                    Sequence temp = new Sequence(
                        new NPBehave.Action(() => {
                            ShowAssistanceHideOthers(kappa);
                            InferenceManager.UnregisterAllInferences();
                            UpdateTextAssistancesDebugWindow("Kappa");
                            MATCH.Utilities.Logger.Instance.Log(this.GetId(), MethodBase.GetCurrentMethod().ReflectedType.Name, MethodBase.GetCurrentMethod().Name, "Kappa");
                        }),
                        new WaitUntilStopped()
                    );

                    return temp;
                }
                
                
                Sequence AssistanceZeta()
                {
                    /*Assistances.GradationVisual.GradationVisual epsilon1 = Assistances.GradationVisual.Factory.Instance.CreateDialogOneButton("Tutorial-Epsilon-1", "", "Félicitations! Le tutoriel est maintenant terminé. Touchez le bouton ci-dessous pour commencer le test de l'application!", "Commencer le test", delegate(System.Object o, EventArgs e)
                    {
                        gameObject.transform.parent.Find("DustingTable").gameObject.SetActive(true);
                        gameObject.SetActive(false);
                    }, Assistances.Buttons.Button.ButtonType.ClosingButton, InteractionCube.transform);*/

                    Assistances.GradationVisual.GradationVisual zeta1 = Assistances.GradationVisual.Factory.Instance.CreateDialog2WithButtons("Tutorial-Zeta-1", "", "Félicitations! Le tutoriel est maintenant terminé. Lorsque vous serez prêt (vous pouvez faire une pause), touchez le bouton ci-dessous pour commencer l'évaluation.", "Commencer l'évaluation", delegate (System.Object o, EventArgs e)
                    {
                        gameObject.transform.parent.Find("DustingTable").gameObject.SetActive(true);
                        gameObject.SetActive(false);
                    }, Assistances.Buttons.Button.ButtonType.ClosingButton, /*InteractionSurfaceToCleanDialog.transform*/ InteractionSurfaceToClean.transform);

                    Assistances.AssistanceGradationExplicit zeta = MATCH.Assistances.Factory.Instance.CreateAssistanceGradationExplicit("Tutorial-Zeta");
                    zeta.transform.parent = transform;

                    zeta.AddAssistance(zeta1, Assistances.Buttons.Button.ButtonType.ClosingButton, null);

                    AssistancesDusting.Add(zeta, false);

                    zeta.Init();

                    Sequence temp = new Sequence(
                        new NPBehave.Action(() => {
                            ShowAssistanceHideOthers(zeta);
                            InferenceManager.UnregisterAllInferences();
                            UpdateTextAssistancesDebugWindow("Zeta");
                            MATCH.Utilities.Logger.Instance.Log(this.GetId(), MethodBase.GetCurrentMethod().ReflectedType.Name, MethodBase.GetCurrentMethod().Name, "Zeta");
                        }),
                        new WaitUntilStopped()
                        );

                    return temp;
                }

                void CallbackInteractionSurfaceRagTouched(System.Object o, EventArgs e)
                {
                    //UpdateConditionWithMatrix(ConditionRagTaken);
                }

                void ShowAssistanceHideOthers(Assistances.AssistanceGradationExplicit assistance)
                {
                    List<Assistances.AssistanceGradationExplicit> keys = new List<Assistances.AssistanceGradationExplicit>(AssistancesDusting.Keys);

                    //foreach(KeyValuePair<Assistances.AssistanceGradationExplicit, bool> assistanceDusting in AssistancesDusting)
                    foreach (Assistances.AssistanceGradationExplicit key in keys)
                    {
                        if (assistance == key)
                        {
                            if (AssistancesDusting[assistance] == false)
                            {
                                assistance.RunAssistance();
                                AssistancesDusting[assistance] = true;
                            }
                        }
                        else if (AssistancesDusting[key])
                        {
                            key.StopAssistance();
                            AssistancesDusting[key] = false;
                        }
                    }
                }
            }

        }
    }
}
